name: Build docker image

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'docker-compose*'

jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml

  generate_docker_image:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build preview image
      uses: ./.github/workflows/build_image.yml
      env:
        TAG_START: 'preview_'
        UPDATE_DOCKER_HUB_DESCRIPTION: 'false'
        TAGS: |
          totonyus/ydl_api_ng:preview

    - name: Build image
      uses: ./.github/workflows/build_image.yml
      env:
        TAG_START: 'latest_'
        UPDATE_DOCKER_HUB_DESCRIPTION: 'false'
        TAGS: |
          totonyus/ydl_api_ng:latest
          totonyus/ydl_api_ng:preview