name: Unit tests

on:
  push:
    branches-ignore:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'docker-compose*'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docker-compose*'
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        mkdir ${{ github.workspace }}/logs
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/pip_requirements
        pip install pytest

    - name: Run tests with pytest
      run: python3 -m pytest ${{ github.workspace }}/unit_tests.py